[build]
  command = ""
  publish = "/"

# Ensure YAML files are served correctly
[[headers]]
  for = "/*.yml"
  [headers.values]
    Content-Type = "text/yaml; charset=utf-8"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yaml; charset=utf-8"

# Redirect /admin → /admin/index.html
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
