[build]
  # No build step, since your site is plain HTML/CSS/JS
  command = ""
  publish = "/"

# Ensure YAML and config files are served with correct MIME type
[[headers]]
  for = "/*.yml"
  [headers.values]
    Content-Type = "text/yml; charset=utf-8"

[[headers]]
  for = "/admin/config.yml"
  [headers.values]
    Content-Type = "text/yml; charset=utf-8"
