site_url: "https://medzonesupplies.netlify.app"

backend:
  name: github
  repo: ellyshitiavai/medzonesupply   # your GitHub repo
  branch: main
  base_url: https://auth.decapcms.org # Decap free auth server

media_folder: "assets/images/uploads"   # where images are stored in repo
public_folder: "/assets/images/uploads" # how they’re served on site

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
