backend:
  name: github
  repo: ellyshitiavai/medzonesupply   # Your GitHub repo
  branch: main                         # Branch to commit content
  auth_type: implicit
  site_domain: https://medzonesupply.netlify.app
  base_url: https://api.github.com

media_folder: "assets/images/uploads"   # Where images are stored in repo
public_folder: "/images/uploads"        # How images are referenced on the site

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
